### ISSUE TITLE
这个库什么时候维护

### ISSUE THREAD

**Issue by TLHorse** [poboke/EasySIMBL-Bundle-Template#3]
我看到readme里面写的支持xcode6、7，可是现在都xcode11了。我看到这个库感觉挺好的，可是我用天气xcode11运行错误一大把，这个库准备什么时候维护呢？求求作者了，千万不要delete，也不要archive。因为我知道你的博客poboke，所以我就用中文写了issue。

以下是我遇到的问题：
<img width="860" alt="截屏" src="https://user-images.githubusercontent.com/38977108/77387744-30a20500-6dc9-11ea-9821-18f4e698f85b.png">
我就随便建了个项目，然后什么都没改，直接按照您博客上的步骤build，这么多错误就出现了。

求求您了，这个库太好了，不要放弃！

**Comment by TLHorse** [comment]
算了吧，已经有替代方案了。谢谢！

**Comment by poboke** [comment]
@MaTianlai 不好意思，之前忘记看Issues了，我刚才试了一下可以编译通过，我的Xcode版本号是11.2.1。
看你的报错提示，应该是在那个路径创建目录时报错了，可能是权限问题导致的。
你可以先试试手动创建`/Library/Application Support/SIMBL/Plugins/`这个目录，应该就不会报错了。
